version: '3.8'

services:
  order-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order.api:
    build:
      context: .
      dockerfile: Services/Order/Presentation/Order.Api/Dockerfile
    container_name: order.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Main=Server=host.docker.internal;Database=OrderDb;User Id=sa;Password=abc123;TrustServerCertificate=True;
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@order-rabbitmq:5672;
    depends_on:
     - order-rabbitmq
      
    


